version: "3.9"

services:
  web:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: micro-template-web
    image: micro-template/nginx-lua:1.0
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
      - ./runtime/nginx:/var/log/nginx
      - .:/app
    ports:
      - "8080:80"
    networks:
      - micro-template-network
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: micro-template-app
    image: micro-template/php:8.1
    volumes:
      - .:/app
      - ./../packages:/packages
    networks:
      - micro-template-network

networks:
  micro-template-network:
    driver: bridge
